//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleCategories = new HashSet<ArticleCategory>();
            this.ArticleComments = new HashSet<ArticleComment>();
            this.ArticleTags = new HashSet<ArticleTag>();
        }
    
        public int ArticleId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Keywords { get; set; }
        public string MainContent { get; set; }
        public string SideContent { get; set; }
        public string ListItemContent { get; set; }
        public int ViewRequests { get; set; }
        public string URLLink { get; set; }
        public string PreviewImg { get; set; }
        public bool isCopied { get; set; }
        public string PrimaryCategory { get; set; }
    
        public virtual ICollection<ArticleCategory> ArticleCategories { get; set; }
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
    }
}
