//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ErrorId { get; set; }
        public int RefId { get; set; }
        public string ErrorMethod { get; set; }
        public string ErrorText { get; set; }
        public System.DateTime ErrorDate { get; set; }
    }
}
