//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.ArticleTags = new HashSet<ArticleTag>();
            this.TagCategories = new HashSet<TagCategory>();
        }
    
        public int TagId { get; set; }
        public string TagName { get; set; }
        public string TagUrl { get; set; }
    
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
        public virtual ICollection<TagCategory> TagCategories { get; set; }
    }
}
